<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Activity1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and its Operation

Sum = A + B

In [33]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
C = A + B
print("This is array A")
print(A)
print("This is array B")
print(B)
print("This is the summation of A and B")
print(C)

This is array A
[[-5  0]
 [ 4  1]]
This is array B
[[ 6 -3]
 [ 2  3]]
This is the summation of A and B
[[ 1 -3]
 [ 6  4]]


Difference#1= A - B

In [38]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
C = A - B
print("This is array A")
print(A)
print("This is array B")
print(B)
print("This is the summation of A and B")
print(C)

This is array A
[[-5  0]
 [ 4  1]]
This is array B
[[ 6 -3]
 [ 2  3]]
This is the summation of A and B
[[-11   3]
 [  2  -2]]


Difference#2 = B - B

In [37]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
C = B - B
print("This is array B")
print(B)
print("This is the summation of A and B")
print(C)

This is array B
[[ 6 -3]
 [ 2  3]]
This is the summation of A and B
[[0 0]
 [0 0]]
