<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Transpose



In [20]:
#3x3 Matrix 
import numpy as np  #to call the module of array
a = np.array([[3,0,1],[12,6,10],[7,15,9]]) #set value for the 3x3 matrix array
print("The Value for Matrix A is: \n",a) # We print the value to see if it works
print("\nThe Transposed Value of Matrix A is: ")
b = np.transpose(a) # put another variable name and use the transpose function to a and see what will happened
print(b) # display the transposed value of Matrix a

The Value for Matrix A is: 
 [[ 3  0  1]
 [12  6 10]
 [ 7 15  9]]

The Transposed Value of Matrix A is: 
[[ 3 12  7]
 [ 0  6 15]
 [ 1 10  9]]


In [24]:
#4x4 Matrix
#We already called the numpy module in previous code cell
matrix = np.array([[2.2,3,5,10],[12,4,6,4],[10,9,15,20],[22,3.5,7,8]])#set value for the 4x4 matrix array
print("The value of the Matrix is : \n ",matrix)# We Display the value to see if it works
transposed = np.transpose(matrix)
print("\nThe Transposed Value of Matrix is: \n",transposed)

The value of the Matrix is : 
  [[ 2.2  3.   5.  10. ]
 [12.   4.   6.   4. ]
 [10.   9.  15.  20. ]
 [22.   3.5  7.   8. ]]

The Transposed Value of Matrix is: 
 [[ 2.2 12.  10.  22. ]
 [ 3.   4.   9.   3.5]
 [ 5.   6.  15.   7. ]
 [10.   4.  20.   8. ]]


#inverse

In [28]:
#We already called the numpy module in previous code cell
#We try to  inverse the given matrix above.
#3x3 MATRIX INVERSE
#a = np.array([[3,0,1],[12,6,10],[7,15,9]])
inverse3x3 = np.linalg.inv(a) # we use the given values in Matrix A on 3x3 
print('The Inverse value of Matrix a is : \n ' , inverse3x3) # we Display the values

The Inverse value of Matrix a is : 
  [[ 0.64       -0.1         0.04      ]
 [ 0.25333333 -0.13333333  0.12      ]
 [-0.92        0.3        -0.12      ]]


In [29]:
#We already called the numpy module in previous code cell
#We try to  inverse the given matrix above.
#4x4 MATRIX INVERSE
#matrix = np.array([[2.2,3,5,10],[12,4,6,4],[10,9,15,20],[22,3.5,7,8]])
inverse4x4 = np.linalg.inv(matrix)# we use the given values in Matrix on 4x4 
print('The Inverse value of Matrix a is : \n ' , inverse4x4)# we Display the values

The Inverse value of Matrix a is : 
  [[ 0.0877193   0.06140351 -0.07017544  0.03508772]
 [ 1.54385965  1.48070175 -0.83508772 -0.58245614]
 [-1.4245614  -0.95719298  0.77964912  0.31017544]
 [ 0.32982456  0.02087719 -0.12385965  0.01192982]]
