<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Application_of_Linear_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##System of Linear Equation

###Systems of Linear Equations can be solved with arrays and NumPy.

In [9]:
import numpy as np

A = np.array([[4,5],[3,-2]])
print(A)
print()
B = np.array([[7],[11]])
print(B)
invA = np.linalg.inv(A)
print()
print(invA)
print()
print(np.dot(invA,B))
#print(np.linalg.inv(A).dot(B))

[[ 4  5]
 [ 3 -2]]

[[ 7]
 [11]]

[[ 0.08695652  0.2173913 ]
 [ 0.13043478 -0.17391304]]

[[ 3.]
 [-1.]]


In [10]:
X = np.linalg.solve(A,B)
print(X)

[[ 3.]
 [-1.]]


In [13]:
from scipy.linalg import solve
print(solve(A,B))

[[ 3.]
 [-1.]]
