<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Value (linalg)

In [1]:
import numpy as np

A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A)

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]


linalg.det

In [6]:
print(np.linalg.det(A))
#round up
print("the round up value")
print(round(np.linalg.det(A)))

-13.999999999999996
the round up value
-14
