<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Eigenvalues_and_Eigenvectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
A = np.array([[-12,3],[4,1]])
B = np.array([[0],[0]])
inv_A = np.linalg.inv(A)
dot = np.dot(inv_A,B)
print(A)
print(B)
print(inv_A)
print(dot)


[[-12   3]
 [  4   1]]
[[0]
 [0]]
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]
[[0.]
 [0.]]
[-12.86545993   1.86545993]
[[-0.96081717 -0.2114717 ]
 [ 0.27718292 -0.97738412]]


In [17]:
#Example 1
C = np.array([[-6,3],[4,5]])
w,v = np.linalg.eig(C)
print(w)
print(v.round())


[-7.  6.]
[[-1. -0.]
 [ 0. -1.]]


In [34]:
#example 2 
A = np.array([[2,2,4],[1,3,5],[2,3,4]])
w,v = np.linalg.eig(A)
print("Eigenvalues are \n ")
print(w.round())
print("Eigenvectors are  \n ")
print(v.round())
print()
print(np.dot(A,v.round()))

Eigenvalues are 
 
[ 9.  1. -1.]
Eigenvectors are  
 
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]

[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]


In [45]:
f = np.array([[0],[-1],[1]])
g = np.dot(A,f)
print(g)

[[2]
 [2]
 [1]]
