<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [57]:
print("Student A + Student B + Student C = 89") #problem : find the value of A,B and C
print("A+B+C=89")#the Equation according to the given problem
print("C-6+3C+C = 89")#given that A = C-6 B = 3C we can solve for C using subsitution
print("5C=95")
print("C=19")
C= 19 # the value of C using subsitution
A = C-6 # solving for the value of A
print("the student A has" )
print(A) #displaying value of A
B = 3*C #Solving for the value of B
print("the student B has" )
print(B)#displaying Value of B
print()
print("proof that the values are correct") #Showing that the values and the equation is correct
print("A+B+C =")
print(A+B+C)

Student A + Student B + Student C = 89
A+B+C=89
C-6+3C+C = 89
5C=95
C=19
the student A has
13
the student B has
57

proof that the values are correct
A+B+C =
89


##Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [58]:
import numpy as np 
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
print("----------------------------------------------------------------------------------------")
A_= np.linalg.inv(A)
print(A_)
print("----------------------------------------------------------------------------------------")
B = np.array([[5],[15],[-20]])
print(B)

#A multiply A to its inverse ----------- AA^-1X = B*A^-1
print("----------------------------------------------------------------------------------------")
#AA'
AA_ = np.dot(A,A_)
print(AA_)
print("----------------------------------------------------------------------------------------")
#A'B
BA_ = np.dot(A_,B)
print("the Unknown Variables Are:")
print(BA_)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
----------------------------------------------------------------------------------------


LinAlgError: ignored

This is an Error because the linear equation has inconsitency that cause the equation unsolvable. The reason why is that we cannot inverse the array A because -12 should be a positive, If we change the sign the program will run but the proof of the linear equation will be false because the given value of the variables is too large. As I observe, I think that in array there only one negative value for each bracket[] to allow us to inverse the matrix and solve for the value of variables. 

##Problem 3. Consider the matrix, (40 points)

In [26]:
import numpy as np
from scipy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])# the Matrix problem
print(A)
w,v = np.linalg.eig(A) #getting eigenvalues and eigenvectors using linalg.eig
print("Eigenvalues are \n ")
print(w.round()) #displaying of Eigenvalues
print("Eigenvectors are  \n ")
print(v.round())#displaying of Eigenvectors

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
Eigenvalues are 
 
[-1.  3.  2.]
Eigenvectors are  
 
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
