<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np 
A = np.array([[4,10,8],[10,26,26],[8,26,61]])
print(A)
print("----------------------------------------------------------------------------------------")
A_ = np.linalg.inv(A)
print(A_)
print("----------------------------------------------------------------------------------------")
B = np.array([[44],[128],[214]])
print(B)

#A multiply A to its inverse ----------- AA^-1X = B*A^-1
print("----------------------------------------------------------------------------------------")
#AA'
AA_ = np.dot(A,A_)
print(AA_)
print("----------------------------------------------------------------------------------------")
#A'B
BA_ = np.dot(A_,B)
print(BA_)


[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
----------------------------------------------------------------------------------------
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]
----------------------------------------------------------------------------------------
[[ 44]
 [128]
 [214]]
----------------------------------------------------------------------------------------
[[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 3.73034936e-14  1.00000000e+00  5.55111512e-17]
 [ 4.44089210e-15  3.77475828e-15  1.00000000e+00]]
----------------------------------------------------------------------------------------
[[-8.]
 [ 6.]
 [ 2.]]
