<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [ ]:
import numpy as np #Import library 
#square matrix is same length and width so 5x5
SquareMatrix = np.array([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0],[4,0,0,0,0],[5,0,0,0,0]]) #set a 5x5 matrix
print("this is the square matrix")
print(SquareMatrix) #display the matrix

this is the square matrix
[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


#Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [46]:
# import numpy as np
Matrix = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]) #make a matrix that below the diagonal is zero
diagonal = np.triu(Matrix)
print(diagonal)# display matrix

[[ 1  2  3  4]
 [ 0  5  6  7]
 [ 0  0  9 10]
 [ 0  0  0 13]]


#Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [49]:
import numpy as np
#symmetric matrix has different values in diagonal but the sides looks like mirror
symmetric = np.array([[1,2,3],[2,5,8],[3,8,9]])
print("symmetric form of matrix A")
print(symmetric)#display the Matrix Values
symmetric1 = np.transpose(symmetric)
print("transpose of the matrix")
print(symmetric1)


symmetric form of matrix A
[[1 2 3]
 [2 5 8]
 [3 8 9]]
transpose of the matrix
[[1 2 3]
 [2 5 8]
 [3 8 9]]


#Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [50]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C)
print("this is the inverse of Matrix C")
C_ = np.linalg.inv(C)#use linalg.inv to inverse the matrix
print(C_)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
this is the inverse of Matrix C
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


#Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [53]:
determinant = np.linalg.det(C)
print(C)
print("the determinant of Matrix C")
print(round(determinant))


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
the determinant of Matrix C
5


#Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [33]:
import numpy as np 
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
print(A)
print("----------------------------------------------------------------------------------------")
A_ = np.linalg.inv(A) #inverse the Matrix A
print(A_)
print("----------------------------------------------------------------------------------------")
B = np.array([[3.4],[8.8],[19.2]])
print(B)

#A multiply A to its inverse ----------- AA^-1X = B*A^-1
print("----------------------------------------------------------------------------------------")
#AXA'
AA_ = np.dot(A,A_)
print(AA_)
print("----------------------------------------------------------------------------------------")
#A'X B
BA_ = np.dot(A_,B)
print("the Unknown Variables Are:")
print(BA_)


[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
----------------------------------------------------------------------------------------
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
----------------------------------------------------------------------------------------
[[ 3.4]
 [ 8.8]
 [19.2]]
----------------------------------------------------------------------------------------
[[ 1.00000000e+00 -4.44089210e-16 -1.66533454e-16]
 [-1.77635684e-15  1.00000000e+00 -2.22044605e-16]
 [-2.22044605e-15 -1.33226763e-15  1.00000000e+00]]
----------------------------------------------------------------------------------------
the Unknown Variables Are:
[[0.2]
 [0.4]
 [0.8]]
