<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Given



In [59]:
import numpy as np
w= np.array([[1,-3],[2,-2],[3,1]])
print("Vector w")
print(w)

x= np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print("Vector x")
print(x)

y= np.array([[1,2,0],[0,-1,2]])
print("Vector y")
print(y)

z= np.array([[0,1,],[2,3]])
print("Vector z")
print(z)


Vector w
[[ 1 -3]
 [ 2 -2]
 [ 3  1]]
Vector x
[[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]
Vector y
[[ 1  2  0]
 [ 0 -1  2]]
Vector z
[[0 1]
 [2 3]]


#Problem 1 a-c

In [58]:
print("problem a answer")
print("wy")
a = np.dot(w,y)
print(a)

print("\n problem b answer")
print("z+z")
b=np.add(z,z)
print(b)

print("\n problem c answer")
print("3x")
c=np.multiply(3,x)
print(c)

problem a answer
wy
[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]

 problem b answer
z+z
[[0 2]
 [4 6]]

 problem c answer
3x
[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


#Problem 2

In [56]:
print("A")
yw = np.dot(y,w)
product= np.power(yw,2)
print(product)
print("false \n")

print("B")
p2b= np.subtract(a,x)
print(p2b)
print("true \n")

print("C")
d= np.dot(y,w)
p2c= np.subtract(d,z^2)
print(p2c)
print("false")

A
[[25 49]
 [16 16]]
false 

B
[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]
true 

C
[[  3 -10]
 [  4   3]]
false
