<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vector Space Operations

In [ ]:
import numpy as np
A= np.array([4,3])
B= np.array([2,-5])
print("Vector A is ",A)
print("Vector A is ",B)

In [ ]:

ball1= np.array([1,2,3])
ball2= np.array([0,1,-1])
pool = np.array([ball1,ball2])
print(pool.shape)
print (pool.size)
pool.ndim

#Vector Addition

In [ ]:
import numpy as np
A= np.array([4,3])
B= np.array([2,-5])
R = A +B
R

In [65]:
P= np.add(A,B)
P

array([ 6, -2])

#Vector Subtraction

In [61]:
R = np.subtract(A,B)
R

array([2, 8])

##Vector Scaling



In [62]:
C = np.array([1,5,8,9])
S= 5*C
S

array([ 5, 25, 40, 45])

In [63]:
C = np.array([1,5,8,9])
S= np.multiply(5,C)
S

array([ 5, 25, 40, 45])

# Vector Cross Product

In [51]:
import numpy as np
D = np.array([2,3])
E = np.array([1,7])
output = np.cross(D,E)
output

array(11)

In [56]:
F = np.array([2,3,4])
G = np.array([1,7,0])
output = np.cross(F,G)
output

array([-28,   4,  11])

#Vector Dot Product

In [66]:
H = np.dot(F,G)
H

23