<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Linear Transformation **

In [16]:
import numpy as np 
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
print(A)
print("----------------------------------------------------------------------------------------")
A_ = np.linalg.inv(A)
print(A_)
print("----------------------------------------------------------------------------------------")
B = np.array([[5],[6],[8]])
print(B)

#A multiply A to its inverse ----------- AA^-1X = B*A^-1
print("----------------------------------------------------------------------------------------")
#AA'
AA_ = np.dot(A,A_)
print(AA_)
print("----------------------------------------------------------------------------------------")
#A'B
BA_ = np.dot(A_,B)
print("the Unknown Variables Are:")
print(BA_)


[[1 1 1]
 [1 2 2]
 [1 2 3]]
----------------------------------------------------------------------------------------
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
----------------------------------------------------------------------------------------
[[5]
 [6]
 [8]]
----------------------------------------------------------------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------------------------------------------------------------------------------
the Unknown Variables Are:
[[ 4.]
 [-1.]
 [ 2.]]
