<a href="https://colab.research.google.com/github/aaronbened/Linear-Algebra-58020/blob/main/Question_2_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
A = np.array([[1.44,-0.36,5.52,0.00],[-0.36,10.33,-7.78,0.00],[5.52,-7.78,28.40,9.00],[0.00,0.00,9.00,61.00]])
print(A)
print("----------------------------------------------------------------------------------------")
A_ = np.linalg.inv(A) #inverse the Matrix A
print(A_)
print("----------------------------------------------------------------------------------------")
B = np.array([[0.04],[-2.15],[0],[0.88]])
print(B)

#A multiply A to its inverse ----------- AA^-1X = B*A^-1
print("----------------------------------------------------------------------------------------")
#AXA'
AA_ = np.dot(A,A_)
print(AA_)
print("----------------------------------------------------------------------------------------")
#A'X B
BA_ = np.dot(A_,B)
print("the Unknown Variables Are:")
print(BA_)
print("----------------------------------------------------------------------------------------")
print("proving:")
print(np.dot(A,BA_))

[[ 1.44 -0.36  5.52  0.  ]
 [-0.36 10.33 -7.78  0.  ]
 [ 5.52 -7.78 28.4   9.  ]
 [ 0.    0.    9.   61.  ]]
----------------------------------------------------------------------------------------
[[ 7.77168524 -1.17747896 -1.92302884  0.28372557]
 [-1.17747896  0.30194402  0.32686043 -0.04822531]
 [-1.92302884  0.32686043  0.52297668 -0.07716049]
 [ 0.28372557 -0.04822531 -0.07716049  0.02777778]]
----------------------------------------------------------------------------------------
[[ 0.04]
 [-2.15]
 [ 0.  ]
 [ 0.88]]
----------------------------------------------------------------------------------------
[[ 1.00000000e+00 -4.01361614e-16 -6.30862532e-17  1.16162224e-16]
 [ 1.98370038e-15  1.00000000e+00 -1.03600104e-15  9.55168729e-17]
 [ 5.71764858e-15 -4.64905892e-16  1.00000000e+00  4.02455846e-16]
 [ 1.66533454e-16 -6.03683770e-16  4.30211422e-16  1.00000000e+00]]
----------------------------------------------------------------------------------------
the Unknown Variables Ar